# Generated by Django 5.1.7 on 2025-03-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankPages', '0002_alter_transaction_amount_alter_transaction_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
